# Generated by Django 3.0.8 on 2020-07-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_instauser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTwo',
        ),
    ]
